[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["cd packages/database && npx prisma generate && cd ../../apps/api && pnpm build"]

[start]
cmd = "cd apps/api && node dist/server.js"